# Generated by Django 5.0.6 on 2024-06-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_pub_date',
            field=models.IntegerField(verbose_name='year published'),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0, verbose_name='votes')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieDatabase.movies')),
            ],
        ),
    ]
