# Generated by Django 5.0.6 on 2024-06-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDatabase', '0002_alter_movies_movie_pub_date_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
    ]
