# Generated by Django 5.0.6 on 2024-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDatabase', '0003_rename_movies_movie_rename_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image_url',
            field=models.CharField(default='https://www.kindpng.com/picc/m/18-189751_movie-placeholder-hd-png-download.png', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_short_description',
            field=models.CharField(default='No description available', max_length=1000),
        ),
    ]
